apiVersion: v1 # Menggunakan versi API inti (core) Kubernetes untuk resource Secret
kind: Secret   # Tipe resource ini adalah Secret, digunakan untuk menyimpan data sensitif seperti password secara lebih aman daripada ConfigMap
metadata:      # Informasi identitas dari resource ini
  name: karsajobs-mongo-secret # Nama Secret ini, akan dirujuk oleh Deployment backend dan StatefulSet MongoDB
data:                                               # Berisi data sensitif yang nilainya wajib dalam format enkode Base64
  MONGO_ROOT_USERNAME: YWRtaW4=                     # Nilai ini adalah "admin" yang telah di-encode ke Base64
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA== # Nilai ini adalah "supersecretpassword" yang telah di-encode ke Base64
